databases:
  - name: budgetdb
    databaseName: budget_pro
    user: ometman
    plan: free

services:
  - type: web
    name: budget-app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: postgres://ometman:rawrObwWNEXTRS2AKJ07KfiViZlHZmfV@dpg-cn9na68cmk4c73a13930-a.oregon-postgres.render.com/budget_pro
        fromDatabase:
          name: budgetdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default